name: integration

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - run: mkdir build
    - run: cd build
    - run: git clone https://github.com/XAMPPRocky/tokei.git --branch v12.1.2
    - run: cd tokei
    - run: cargo build --release
    - run: cd ../..
    - run: mkdir -p upload/${{ matrix.os }}
    - run: cd build/tokei/target/release/tokei upload/${{ matrix.os }}/
    - run: upload/${{ matrix.os }}/tokei --version
    - uses: actions/upload-artifact@v2
      with:
        name: upload
        path: upload
